### PR TITLE
updateproject function

### PR DESCRIPTION
**Pull request by tututuana**

### CODE REVIEW

**Comment by tututuana** [comment]
i dont know if im understand updateproject function correct. Can you explain it a bit?

**Comment by BetaPictoris** [comment]
`updateProject` is used to update the `project` command (ie. getting the remote version from `checkForUpdates` and using git to install the latest version of `project`).

**Comment by tututuana** [comment]
> `updateProject` is used to update the `project` command (ie. getting the remote version from `checkForUpdates` and using git to install the latest version of `project`).

i did it on new update you can merge right now if you want.

**Comment by BetaPictoris** [comment]
Merging to `alpha`...

**Comment by BetaPictoris** [comment]
Merged with #5.

**Pull request closed without merging**
